### ISSUE TITLE
executeInSelenium: \WebDriver instead of \Facebook\WebDriver\Remote\RemoteWebDriver is offered

### ISSUE THREAD

**Issue by mirao** [diego-vieira/vscode-codeception-snippets#1]
**Steps:**

- insert the snippet `executeInSelenium`

**Expected result:**

- `$I->executeInSelenium(function(\Facebook\WebDriver\Remote\RemoteWebDriver $webdriver) { $webdriver->get('url'); });`

**Actual result:**

- `$I->executeInSelenium(function(\WebDriver $webdriver) { $webdriver->get('url'); });`

It doesn't work for me, I get the error:
- - -
[TypeError] Argument 1 passed to Codeception\Test\Cept::{closure}() must be an instance of WebDriver, instance of Facebook\WebDriver\
Remote\RemoteWebDriver given, called in /home/mira/codeception/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php on l
ine 2113
- - -
**Used SW:**

- VSCode 1.10.2
- Codeception Snippets 0.0.2
- Codeception 2.2.9

**Comment by dv336699** [comment]
@mirao let me know if 0.0.3 works for you.
Feel free to send a PR.

Cheers

**Comment by mirao** [comment]
@diego-vieira : Works for me with 0.0.4, thanks for quick fix.
